[package]
name = "sn-tracer-egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
dirs = "5.0.1"
egui = "0.23.0"
env_logger = "0.10.1"
log = "0.4.20"
tokio-serial = "5.4.4"
